using System.Reflection; 
using System.Runtime.InteropServices; 

//This file is auto generated by prebuild.bat 
[assembly: AssemblyTitle("Primrose.Expressions")] 
[assembly: AssemblyDescription("")] 
[assembly: AssemblyConfiguration("")] 
[assembly: AssemblyCompany("")] 
[assembly: AssemblyProduct("Primrose.Expressions")] 
[assembly: AssemblyCopyright("Copyright ? 2019-2020. All rights reserved.")] 
[assembly: AssemblyTrademark("")] 
[assembly: AssemblyCulture("")] 

[assembly: ComVisible(false)] 
[assembly: AssemblyVersion("0.0.*")] 
[assembly: AssemblyFileVersion("0.0.02007.0401")] 

