namespace Primrose.Expressions 
{ 
  //This file is auto generated by prebuild.bat 
  /// <summary>Provides internal build information for this project</summary> 
  public static class Build 
  { 
   /// <summary>The time of build</summary> 
   public const string Time = "Sat 07/25/2020 12:57:35.67"; 
   /// <summary>The date of build in YYYYMMDD format</summary> 
   public const string BuildDate = "20200725"; 
   /// <summary>The daily revision number of the build</summary> 
   public const string Revision = "00"; 
  } 
} 
