namespace Primrose.Expressions 
{ 
  //This file is auto generated by prebuild.bat 
  /// <summary>Provides internal build information for this project</summary> 
  public static class Build 
  { 
   /// <summary>The time of build</summary> 
   public const string Time = "Tue 01/06/2021  6:50:21.62"; 
   /// <summary>The date of build in YYYYMMDD format</summary> 
   public const string BuildDate = "20210106"; 
   /// <summary>The daily revision number of the build</summary> 
   public const string Revision = "00"; 
  } 
} 
