namespace Primrose.Expressions 
{ 
  //This file is auto generated by prebuild.bat 
  /// <summary>Provides internal build information for this project</summary> 
  public static class Build 
  { 
   /// <summary>The time of build</summary> 
   public const string Time = "Fri 07/24/2020 12:26:52.92"; 
   /// <summary>The date of build in YYYYMMDD format</summary> 
   public const string BuildDate = "20200724"; 
   /// <summary>The daily revision number of the build</summary> 
   public const string Revision = "07"; 
  } 
} 
