//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primrose.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primrose.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///BOOLEAN = true
        ///INT = 1
        ///INT4 = 4, 5, 6, 7
        ///FLOAT = 1.2
        ///FLOAT4 = 23, 3.4, 0.5, .56
        ///
        ///[Test1]
        ///SHORT = 3
        ///SHORT2 = 5, 7
        ///SHORT3 = 9, 11, 13
        ///SHORT4 = 15, 17, 19, 21
        ///
        ///[Test2]
        ///STRING = This is one
        ///STRING_ARRAY = two, three, four
        ///
        ///[Test3]
        ///ENUM = ONE | TWO
        ///BOOLEAN_ARRAY = true, false, true, false
        ///.
        /// </summary>
        internal static string INI_ReadAndMatch {
            get {
                return ResourceManager.GetString("INI_ReadAndMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER=InnerA,InnerB,InnerC,InnerD ; for null section
        ///
        ///[TestSubsectionList]
        ///INNER=InnerA,InnerB,InnerC,InnerD
        ///
        ///[TestSubsectionKeyList]
        ///InnerA
        ///InnerB
        ///InnerC
        ///InnerD
        ///
        ///[TestSubSectionRegistryStruct]
        ///1=InnerA
        ///2=InnerB
        ///3=InnerC
        ///4=InnerD
        ///
        ///[INNER]
        ///InnerA
        ///InnerB
        ///InnerC
        ///InnerD
        ///
        ///[InnerA]
        ///VAL1=1
        ///VAL2=2
        ///
        ///[InnerB]
        ///VAL3=3
        ///VAL4=4
        ///
        ///[InnerC]
        ///VAL1=1
        ///VAL3=3
        ///
        ///[InnerD]
        ///VAL1=1
        ///VAL4=4.
        /// </summary>
        internal static string INI_ReadSubSections {
            get {
                return ResourceManager.GetString("INI_ReadSubSections", resourceCulture);
            }
        }
    }
}
