//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primrose.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Primrose.Resource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting ID to AFactoryObject with existing ID &apos;{0}&apos; is not allowed!.
        /// </summary>
        internal static string Error_AFactoryObjectDuplicateID {
            get {
                return ResourceManager.GetString("Error_AFactoryObjectDuplicateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted operation between two arrays of different length..
        /// </summary>
        internal static string Error_ArrayMismatchException {
            get {
                return ResourceManager.GetString("Error_ArrayMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted operation between two arrays of different lengths &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string Error_ArrayMismatchException_length_length {
            get {
                return ResourceManager.GetString("Error_ArrayMismatchException_length_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted assignment of an array of length {0} to {1}..
        /// </summary>
        internal static string Error_ArrayMismatchException_length_type {
            get {
                return ResourceManager.GetString("Error_ArrayMismatchException_length_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to get an non-existent key &apos;{0}&apos; from a cache..
        /// </summary>
        internal static string Error_CacheKeyNotFound {
            get {
                return ResourceManager.GetString("Error_CacheKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to push an item into {0} that has reached capacity limit of {1}..
        /// </summary>
        internal static string Error_CapacityExceededException {
            get {
                return ResourceManager.GetString("Error_CapacityExceededException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to add an existing key &apos;{0}&apos; to a {1}..
        /// </summary>
        internal static string Error_CollectionAddDuplicateKey {
            get {
                return ResourceManager.GetString("Error_CollectionAddDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to add a null key to a {0}..
        /// </summary>
        internal static string Error_CollectionAddNullKey {
            get {
                return ResourceManager.GetString("Error_CollectionAddNullKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to put value of a null key in a {0}..
        /// </summary>
        internal static string Error_CollectionPutNullKey {
            get {
                return ResourceManager.GetString("Error_CollectionPutNullKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to set value to an non-existent key &apos;{0}&apos; in a {1}..
        /// </summary>
        internal static string Error_CollectionSetKeyNotFound {
            get {
                return ResourceManager.GetString("Error_CollectionSetKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to set value of a null key to a {0}..
        /// </summary>
        internal static string Error_CollectionSetNullKey {
            get {
                return ResourceManager.GetString("Error_CollectionSetNullKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid duplicate section [{0}] detected..
        /// </summary>
        internal static string Error_DuplicateINISection {
            get {
                return ResourceManager.GetString("Error_DuplicateINISection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an enum..
        /// </summary>
        internal static string Error_ExpectedEnumException {
            get {
                return ResourceManager.GetString("Error_ExpectedEnumException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is not found!.
        /// </summary>
        internal static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute does not exist!.
        /// </summary>
        internal static string Error_INIFileAttributeNotFound {
            get {
                return ResourceManager.GetString("Error_INIFileAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIKeyList attribute can only be used with string[] data types! ({0}).
        /// </summary>
        internal static string Error_INIKeyListInvalidType {
            get {
                return ResourceManager.GetString("Error_INIKeyListInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; in section &apos;{1}&apos; is not defined!.
        /// </summary>
        internal static string Error_INIKeyNotFound {
            get {
                return ResourceManager.GetString("Error_INIKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIRegistry attribute can only be used with Registry&lt;K,T&gt; data types! ({0}).
        /// </summary>
        internal static string Error_INIRegistryListInvalidType {
            get {
                return ResourceManager.GetString("Error_INIRegistryListInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section &apos;{0}&apos; is not defined!.
        /// </summary>
        internal static string Error_INISectionNotFound {
            get {
                return ResourceManager.GetString("Error_INISectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INISubSectionKeyListAttribute attribute can only be used with a single-level array (T[]) data type! ({0}).
        /// </summary>
        internal static string Error_INISubSectionKeyListInvalidType {
            get {
                return ResourceManager.GetString("Error_INISubSectionKeyListInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INISubSectionListAttribute attribute can only be used with a single-level array (T[]) data type! ({0}).
        /// </summary>
        internal static string Error_INISubSectionListInvalidType {
            get {
                return ResourceManager.GetString("Error_INISubSectionListInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to access invalid index &apos;{0}&apos; of {1}..
        /// </summary>
        internal static string Error_InvalidIndex {
            get {
                return ResourceManager.GetString("Error_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; is not valid on state &apos;{1}&apos;.
        /// </summary>
        internal static string Error_InvalidStateCommandException {
            get {
                return ResourceManager.GetString("Error_InvalidStateCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background object pool for &apos;{0}&apos; has not been created..
        /// </summary>
        internal static string Error_ObjectPoolBackgroundPoolNotCreated {
            get {
                return ResourceManager.GetString("Error_ObjectPoolBackgroundPoolNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a background object pool for &apos;{0}&apos;.
        /// </summary>
        internal static string Error_ObjectPoolDuplicateBackgroundPool {
            get {
                return ResourceManager.GetString("Error_ObjectPoolDuplicateBackgroundPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object to be admitted into the pool &apos;{0}&apos; already exists in the pool!.
        /// </summary>
        internal static string Error_ObjectPoolDuplicateItem {
            get {
                return ResourceManager.GetString("Error_ObjectPoolDuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to parse invalid value &apos;{0}&apos; as {1}..
        /// </summary>
        internal static string Error_RuleConversionException {
            get {
                return ResourceManager.GetString("Error_RuleConversionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to parse a string from an unsupported type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnsupportedParseException {
            get {
                return ResourceManager.GetString("Error_UnsupportedParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to write a string from an unsupported type &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnsupportedWriteException {
            get {
                return ResourceManager.GetString("Error_UnsupportedWriteException", resourceCulture);
            }
        }
    }
}
