namespace Primrose 
{ 
  //This file is auto generated by prebuild.bat 
  /// <summary>Provides internal build information for this project</summary> 
  public static class Build 
  { 
   /// <summary>The time of build</summary> 
   public const string Time = "Thu 31/12/2020 21:13:06.54"; 
   /// <summary>The date of build in YYYYMMDD format</summary> 
   public const string BuildDate = "20203112"; 
   /// <summary>The daily revision number of the build</summary> 
   public const string Revision = "04"; 
  } 
} 
