namespace Primrose 
{ 
  //This file is auto generated by prebuild.bat 
  /// <summary>Provides internal build information for this project</summary> 
  public static class Build 
  { 
   /// <summary>The time of build</summary> 
   public const string Time = "Wed 19/05/2021  5:38:39.12"; 
   /// <summary>The date of build in YYYYMMDD format</summary> 
   public const string BuildDate = "20211905"; 
   /// <summary>The daily revision number of the build</summary> 
   public const string Revision = "01"; 
  } 
} 
