namespace Primrose 
{ 
  //This file is auto generated by prebuild.bat 
  /// <summary>Provides internal build information for this project</summary> 
  public static class Build 
  { 
   /// <summary>The time of build</summary> 
   public const string Time = "Mon 06/29/2020 15:41:12.99"; 
   /// <summary>The date of build in YYYYMMDD format</summary> 
   public const string BuildDate = "20200629"; 
   /// <summary>The daily revision number of the build</summary> 
   public const string Revision = "03"; 
  } 
} 
